/* eslint-disable */
// This file is automatically generated, do not edit!

import "@atcute/client/lexicons";

declare module "@atcute/client/lexicons" {
  namespace SocialPskyActorProfile {
    /** A declaration of a Picosky account profile. */
    interface Record {
      $type: "social.psky.actor.profile";
      /**
       * Maximum string length: 320 \
       * Maximum grapheme length: 32
       */
      nickname?: string;
    }
  }

  namespace SocialPskyFeedPost {
    /** A Picosky post containing at most 12 graphemes. */
    interface Record {
      $type: "social.psky.feed.post";
      /**
       * Text content. \
       * Maximum string length: 1000 \
       * Maximum grapheme length: 64
       */
      text: string;
    }
  }

  interface Records {
    "social.psky.actor.profile": SocialPskyActorProfile.Record;
    "social.psky.feed.post": SocialPskyFeedPost.Record;
  }

  interface Queries {}

  interface Procedures {}
}
